#server:
#  port: 8001
#
#spring:
#  application:
#    # 服务逻辑名称
#    name: light-reading-cloud-book
#  datasource:
#
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/reading_cloud_resource?&serverTimezone=GMT%2B8
#    username: root
#    password: '123456'
#    initial-size: 5
#    min-idle: 5
#    max-active: 30
#    max-wait: 6000
#    test-while-idle: true
#    validation-query: 'select 1 from dual'
#    connect-timeout: 1500
#
#  #---- redis配置  ----#
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password:
#    jedis:
#      pool:
#        #最大连接数据库连接数,设 0 为没有限制
#        max-active: 30
#        #最大等待连接中的数量,设 0 为没有限制
#        max-idle: 10
#        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
#        max-wait: -1ms
#        #最小等待连接中的数量,设 0 为没有限制
#        min-idle: 0
#      lettuce:
#        pool:
#          max-active: 10
#          max-idle: 5
#          max-wait: -1ms
#          min-idle: 0
#        shutdown-timeout: 100ms
#eureka:
#  instance:
#    # 注册服务的IP，而不是逻辑名称
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:1001/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#
#hystrix:
#  threadpool:
#    default:
#      coreSize: 20 #并发执行的最大线程数，默认10
#      maxQueueSize: 1000 #BlockingQueue的最大队列数，默认值-1
#      queueSizeRejectionThreshold: 400
#
#from: dev-environment-1.0...